


export const SEARCH_SELECTED = {
  DESTINATION:'DESTINATION',
  SOURCE:'SOURCE'
}

export const types = {
  OPEN_SEARCH: 'OPEN_SEARCH',
  CLOSE_SEARCH: 'CLOSE_SEARCH',
  SET_DESTINATION: 'SET_DESTINATION',
  SET_SOURCE: 'SET_SOURCE',
  RECEIVE_PREDICTIONS: 'RECEIVE_PREDICTIONS',
  SET_SEARCH_SELECTED: 'SET_SEARCH_SELECTED'
}
